version: 0.2

env:
  secrets-manager:
    TELEGRAM_BOT_TOKEN: "dopamint-secrets:TELEGRAM_BOT_TOKEN"
    TELEGRAM_CHAT_ID: "dopamint-secrets:TELEGRAM_CHAT_ID"
    TELEGRAM_THREAD_ID: "dopamint-secrets:TELEGRAM_THREAD_ID"
    DOPAMINT_EMAIL: "dopamint-secrets:DOPAMINT_EMAIL"
    DOPAMINT_PASSWORD: "dopamint-secrets:DOPAMINT_PASSWORD"
    METAMASK_SEED_PHRASE: "dopamint-secrets:METAMASK_SEED_PHRASE"
    GMAIL_EMAIL: "dopamint-secrets:GMAIL_EMAIL"
    GMAIL_APP_PASSWORD: "dopamint-secrets:GMAIL_APP_PASSWORD"
    GOOGLE_EMAIL: "dopamint-secrets:GOOGLE_EMAIL"
    GOOGLE_PASSWORD: "dopamint-secrets:GOOGLE_PASSWORD"
    GOOGLE_2FA_SECRET: "dopamint-secrets:GOOGLE_2FA_SECRET"
  variables:
    TEST_FILE: "dopamintLogin.spec.ts,create.spec.ts,searchMintSell.spec.ts"
    TEST_NAME: "Dopamint Auto Test"
    S3_BUCKET: "dopamint-test-assets"
    S3_SESSION_KEY: "playwright/googleSession.json"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx playwright install chromium --with-deps
      # Install xvfb for virtual display (needed for headed browser with extensions)
      - apt-get update && apt-get install -y xvfb dbus-x11

  pre_build:
    commands:
      - echo "Preparing test environment..."
      - mkdir -p test-results
      - mkdir -p auth
      # Create .env.telegram for Telegram notifications
      - echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" > .env.telegram
      - echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}" >> .env.telegram
      - echo "TELEGRAM_THREAD_ID=${TELEGRAM_THREAD_ID}" >> .env.telegram
      # Create .env.test for test credentials
      - echo "DOPAMINT_EMAIL=${DOPAMINT_EMAIL}" > .env.test
      - echo "DOPAMINT_PASSWORD=${DOPAMINT_PASSWORD}" >> .env.test
      - echo "METAMASK_SEED_PHRASE=${METAMASK_SEED_PHRASE}" >> .env.test
      - echo "GMAIL_EMAIL=${GMAIL_EMAIL}" >> .env.test
      - echo "GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}" >> .env.test
      - echo "GOOGLE_EMAIL=${GOOGLE_EMAIL}" >> .env.test
      - echo "GOOGLE_PASSWORD=${GOOGLE_PASSWORD}" >> .env.test
      - echo "GOOGLE_2FA_SECRET=${GOOGLE_2FA_SECRET}" >> .env.test
      - echo "S3_BUCKET=${S3_BUCKET}" >> .env.test
      - echo "S3_SESSION_KEY=${S3_SESSION_KEY}" >> .env.test
      # Download Google session from S3
      - echo "Downloading Google session from S3..."
      - 'aws s3 cp s3://${S3_BUCKET}/${S3_SESSION_KEY} auth/googleSession.json || echo "Warning: Could not download session file"'
      # Start D-Bus (required for Chrome)
      - mkdir -p /run/dbus
      - dbus-daemon --system --fork || true

  build:
    commands:
      - echo "Running Playwright tests with virtual display..."
      - chmod +x scripts/run-test.sh
      # Use xvfb-run to create virtual display for headed browser
      - xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./scripts/run-test.sh

  post_build:
    commands:
      - echo "Tests completed!"

artifacts:
  files:
    - test-results/**/*
    - playwright-report/**/*
  name: test-results-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - node_modules/**/*
    - ~/.cache/ms-playwright/**/*
