version: 0.2

env:
  secrets-manager:
    TELEGRAM_BOT_TOKEN: "dopamint-secrets:TELEGRAM_BOT_TOKEN"
    TELEGRAM_CHAT_ID: "dopamint-secrets:TELEGRAM_CHAT_ID"
    TELEGRAM_THREAD_ID: "dopamint-secrets:TELEGRAM_THREAD_ID"
    DOPAMINT_EMAIL: "dopamint-secrets:DOPAMINT_EMAIL"
    DOPAMINT_PASSWORD: "dopamint-secrets:DOPAMINT_PASSWORD"
    METAMASK_SEED_PHRASE: "dopamint-secrets:METAMASK_SEED_PHRASE"
  variables:
    TEST_FILE: "dopamintLogin.spec.ts,create.spec.ts,searchMintSell.spec.ts"
    TEST_NAME: "Dopamint Auto Test"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx playwright install chromium --with-deps
      # Install xvfb for virtual display (needed for headed browser with extensions)
      - apt-get update && apt-get install -y xvfb dbus-x11

  pre_build:
    commands:
      - echo "Preparing test environment..."
      - mkdir -p test-results
      # Create .env.telegram for Telegram notifications
      - |
        cat > .env.telegram << EOF
        TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
        TELEGRAM_THREAD_ID=${TELEGRAM_THREAD_ID}
        EOF
      # Create .env.test for test credentials
      - |
        cat > .env.test << EOF
        DOPAMINT_EMAIL=${DOPAMINT_EMAIL}
        DOPAMINT_PASSWORD=${DOPAMINT_PASSWORD}
        METAMASK_SEED_PHRASE=${METAMASK_SEED_PHRASE}
        EOF
      # Start D-Bus (required for Chrome)
      - mkdir -p /run/dbus
      - dbus-daemon --system --fork || true

  build:
    commands:
      - echo "Running Playwright tests with virtual display..."
      - chmod +x scripts/run-test.sh
      # Use xvfb-run to create virtual display for headed browser
      - xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./scripts/run-test.sh

  post_build:
    commands:
      - echo "Tests completed!"

artifacts:
  files:
    - test-results/**/*
    - playwright-report/**/*
  name: test-results-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - node_modules/**/*
    - ~/.cache/ms-playwright/**/*
